insert into place (id_place, name_place) values (1, 'Jiapeng');
insert into place (id_place, name_place) values (2, 'Prienai');
insert into place (id_place, name_place) values (3, 'Cienfuegos');
insert into place (id_place, name_place) values (4, 'Shal’skiy');
insert into place (id_place, name_place) values (5, 'Changtan');
insert into place (id_place, name_place) values (6, 'Jianghong');
insert into place (id_place, name_place) values (7, 'Samoljica');
insert into place (id_place, name_place) values (8, 'Ntobo');
insert into place (id_place, name_place) values (9, 'Madang');
insert into place (id_place, name_place) values (10, 'Surgut');
insert into place (id_place, name_place) values (11, 'Trzemeszno');
insert into place (id_place, name_place) values (12, 'Katsuura');
insert into place (id_place, name_place) values (13, 'Jdaidet el Matn');
insert into place (id_place, name_place) values (14, 'Beaufort');
insert into place (id_place, name_place) values (15, 'Bajawa');
insert into place (id_place, name_place) values (16, 'Khirdalan');
insert into place (id_place, name_place) values (17, 'Benhong');
insert into place (id_place, name_place) values (18, 'Alebtong');
insert into place (id_place, name_place) values (19, 'Ardirejo');
insert into place (id_place, name_place) values (20, 'Sapataria');
insert into place (id_place, name_place) values (21, 'Jacareí');
insert into place (id_place, name_place) values (22, 'Serra de Santa Marinha');
insert into place (id_place, name_place) values (23, 'Hujirt');
insert into place (id_place, name_place) values (24, 'Nancy');
insert into place (id_place, name_place) values (25, 'Monte Alto');
insert into place (id_place, name_place) values (26, 'Primero de Mayo');
insert into place (id_place, name_place) values (27, 'Donggou');
insert into place (id_place, name_place) values (28, 'Silao');
insert into place (id_place, name_place) values (29, 'Sindang');
insert into place (id_place, name_place) values (30, 'Wangqu');
insert into place (id_place, name_place) values (31, 'Rashaant');
insert into place (id_place, name_place) values (32, 'Pestovo');
insert into place (id_place, name_place) values (33, 'Takokak');
insert into place (id_place, name_place) values (34, 'Matiguás');
insert into place (id_place, name_place) values (35, 'Al ‘Awjah');
insert into place (id_place, name_place) values (36, 'Tashla');
insert into place (id_place, name_place) values (37, 'Jiangdianzi');
insert into place (id_place, name_place) values (38, 'Sudzha');
insert into place (id_place, name_place) values (39, 'Alofi');
insert into place (id_place, name_place) values (40, 'Palermo');
insert into place (id_place, name_place) values (41, 'Tafí del Valle');
insert into place (id_place, name_place) values (42, 'Khōshī');
insert into place (id_place, name_place) values (43, 'Lattes');
insert into place (id_place, name_place) values (44, 'Heqiao');
insert into place (id_place, name_place) values (45, 'Hema');
insert into place (id_place, name_place) values (46, 'Bangshipu');
insert into place (id_place, name_place) values (47, 'Trąbki');
insert into place (id_place, name_place) values (48, 'Petrovsk');
insert into place (id_place, name_place) values (49, 'Piracuruca');
insert into place (id_place, name_place) values (50, 'Prachuap Khiri Khan');
insert into place (id_place, name_place) values (51, 'Svobody');
insert into place (id_place, name_place) values (52, 'Simnas');
insert into place (id_place, name_place) values (53, 'Calapan');
insert into place (id_place, name_place) values (54, 'Lukou');
insert into place (id_place, name_place) values (55, 'Miaotang');
insert into place (id_place, name_place) values (56, 'Wedoro');
insert into place (id_place, name_place) values (57, 'Sidomulyo');
insert into place (id_place, name_place) values (58, 'Maticmatic');
insert into place (id_place, name_place) values (59, 'Tangchijie');
insert into place (id_place, name_place) values (60, 'Urdaneta');
insert into place (id_place, name_place) values (61, 'Pavlovskiy Posad');
insert into place (id_place, name_place) values (62, 'Ponte');
insert into place (id_place, name_place) values (63, 'Zaki Biam');
insert into place (id_place, name_place) values (64, 'Dongfeng');
insert into place (id_place, name_place) values (65, 'Maanas');
insert into place (id_place, name_place) values (66, 'Afaahiti');
insert into place (id_place, name_place) values (67, 'Añelo');
insert into place (id_place, name_place) values (68, 'Flushing');
insert into place (id_place, name_place) values (69, 'Skänninge');
insert into place (id_place, name_place) values (70, 'Sonsón');
insert into place (id_place, name_place) values (71, 'Kamárai');
insert into place (id_place, name_place) values (72, 'Đồi Ngô');
insert into place (id_place, name_place) values (73, 'São Pedro');
insert into place (id_place, name_place) values (74, 'Lodja');
insert into place (id_place, name_place) values (75, 'Lufang');
insert into place (id_place, name_place) values (76, 'Zhifudao');
insert into place (id_place, name_place) values (77, 'Klinan');
insert into place (id_place, name_place) values (78, 'Peyima');
insert into place (id_place, name_place) values (79, 'Sambirejo');
insert into place (id_place, name_place) values (80, 'Horní Štěpánov');
insert into place (id_place, name_place) values (81, 'Morteros');
insert into place (id_place, name_place) values (82, 'Strellc i Epërm');
insert into place (id_place, name_place) values (83, 'Ostashkov');
insert into place (id_place, name_place) values (84, 'Guishan');
insert into place (id_place, name_place) values (85, 'Smiltene');
insert into place (id_place, name_place) values (86, 'Colonia Nicolich');
insert into place (id_place, name_place) values (87, 'Beylagan');
insert into place (id_place, name_place) values (88, 'Maharagama');
insert into place (id_place, name_place) values (89, 'Liujia');
insert into place (id_place, name_place) values (90, 'Xinshichang');
insert into place (id_place, name_place) values (91, 'Edéa');
insert into place (id_place, name_place) values (92, 'Alpedrinha');
insert into place (id_place, name_place) values (93, 'Paris 14');
insert into place (id_place, name_place) values (94, 'Dul’durga');
insert into place (id_place, name_place) values (95, 'Lanta Timur');
insert into place (id_place, name_place) values (96, 'Flor da Rosa');
insert into place (id_place, name_place) values (97, 'Jiuxian');
insert into place (id_place, name_place) values (98, 'Mashan');
insert into place (id_place, name_place) values (99, 'Halat');
insert into place (id_place, name_place) values (100, 'Yuto');
insert into place (id_place, name_place) values (101, 'Chichaoua');
insert into place (id_place, name_place) values (102, 'Zhangjiawo');
insert into place (id_place, name_place) values (103, 'Puttalam');
insert into place (id_place, name_place) values (104, 'Puncaksari');
insert into place (id_place, name_place) values (105, 'Argasari');
insert into place (id_place, name_place) values (106, 'Kallíthiron');
insert into place (id_place, name_place) values (107, 'Peso da Régua');
insert into place (id_place, name_place) values (108, 'Borova');
insert into place (id_place, name_place) values (109, 'Aganan');
insert into place (id_place, name_place) values (110, 'Yanggu');
insert into place (id_place, name_place) values (111, 'Gunungpeundeuy');
insert into place (id_place, name_place) values (112, 'Karangasem Laok');
insert into place (id_place, name_place) values (113, 'Santa Lucía Cotzumalguapa');
insert into place (id_place, name_place) values (114, 'Ipameri');
insert into place (id_place, name_place) values (115, 'Athlone');
insert into place (id_place, name_place) values (116, 'Leteki');
insert into place (id_place, name_place) values (117, 'Lingbeizhou');
insert into place (id_place, name_place) values (118, 'Geneng');
insert into place (id_place, name_place) values (119, 'Laixi');
insert into place (id_place, name_place) values (120, 'Krajan Dua Patempuran');
insert into place (id_place, name_place) values (121, 'Skolkovo');
insert into place (id_place, name_place) values (122, 'Ampanihy');
insert into place (id_place, name_place) values (123, 'Neuquén');
insert into place (id_place, name_place) values (124, 'Corrego Grande');
insert into place (id_place, name_place) values (125, 'Noyakert');
insert into place (id_place, name_place) values (126, 'Utarapasar');
insert into place (id_place, name_place) values (127, 'Maliang');
insert into place (id_place, name_place) values (128, 'Fengcheng');
insert into place (id_place, name_place) values (129, 'Malya');
insert into place (id_place, name_place) values (130, 'Oslo');
insert into place (id_place, name_place) values (131, 'Wenshao');
insert into place (id_place, name_place) values (132, 'Baru');
insert into place (id_place, name_place) values (133, 'Mortka');
insert into place (id_place, name_place) values (134, 'Patos de Minas');
insert into place (id_place, name_place) values (135, 'Angra dos Reis');
insert into place (id_place, name_place) values (136, 'Ordzhonikidzevskaya');
insert into place (id_place, name_place) values (137, 'Xikou');
insert into place (id_place, name_place) values (138, 'Belleville');
insert into place (id_place, name_place) values (139, 'Uničov');
insert into place (id_place, name_place) values (140, 'Tubalan');
insert into place (id_place, name_place) values (141, 'Wuli');
insert into place (id_place, name_place) values (142, 'Zhengmo');
insert into place (id_place, name_place) values (143, 'Shuangxi');
insert into place (id_place, name_place) values (144, 'Khóra');
insert into place (id_place, name_place) values (145, 'Horad Pinsk');
insert into place (id_place, name_place) values (146, 'Arhust');
insert into place (id_place, name_place) values (147, 'Moppo');
insert into place (id_place, name_place) values (148, 'Santa Maria');
insert into place (id_place, name_place) values (149, 'Nowa Góra');
insert into place (id_place, name_place) values (150, 'Gaoliang');
insert into place (id_place, name_place) values (151, 'Gornorechenskiy');
insert into place (id_place, name_place) values (152, 'Praia do Ribatejo');
insert into place (id_place, name_place) values (153, 'Kudang');
insert into place (id_place, name_place) values (154, 'Limanowa');
insert into place (id_place, name_place) values (155, 'Barrouallie');
insert into place (id_place, name_place) values (156, 'Kifrī');
insert into place (id_place, name_place) values (157, 'Esmeralda');
insert into place (id_place, name_place) values (158, 'Yelizovo');
insert into place (id_place, name_place) values (159, 'Yangsan');
insert into place (id_place, name_place) values (160, 'Kovel’');
insert into place (id_place, name_place) values (161, 'Al Qārah');
insert into place (id_place, name_place) values (162, 'Aserrío de Gariché');
insert into place (id_place, name_place) values (163, 'Krasnaya Polyana');
insert into place (id_place, name_place) values (164, 'Lingkou');
insert into place (id_place, name_place) values (165, 'Gaotan');
insert into place (id_place, name_place) values (166, 'Zheleznodorozhnyy');
insert into place (id_place, name_place) values (167, 'Taiping');
insert into place (id_place, name_place) values (168, 'Chucatamani');
insert into place (id_place, name_place) values (169, 'Banjar Batuaji Kaja');
insert into place (id_place, name_place) values (170, 'Gweedore');
insert into place (id_place, name_place) values (171, 'Rancakuya');
insert into place (id_place, name_place) values (172, 'Markog');
insert into place (id_place, name_place) values (173, 'Ungsang');
insert into place (id_place, name_place) values (174, 'Jiangtun');
insert into place (id_place, name_place) values (175, 'Vale da Bajouca');
insert into place (id_place, name_place) values (176, 'Vincennes');
insert into place (id_place, name_place) values (177, 'Heilbronn');
insert into place (id_place, name_place) values (178, 'Huangsha');
insert into place (id_place, name_place) values (179, 'Mbongawani');
insert into place (id_place, name_place) values (180, 'Boychinovtsi');
insert into place (id_place, name_place) values (181, 'Mazamet');
insert into place (id_place, name_place) values (182, 'Topi');
insert into place (id_place, name_place) values (183, 'Vicente Guerrero');
insert into place (id_place, name_place) values (184, 'Conselheiro Lafaiete');
insert into place (id_place, name_place) values (185, 'Nysa');
insert into place (id_place, name_place) values (186, 'Vykhino-Zhulebino');
insert into place (id_place, name_place) values (187, 'Mino');
insert into place (id_place, name_place) values (188, 'Huangyang');
insert into place (id_place, name_place) values (189, 'Delvinë');
insert into place (id_place, name_place) values (190, 'Xinwo');
insert into place (id_place, name_place) values (191, 'Watuka');
insert into place (id_place, name_place) values (192, 'Tottori');
insert into place (id_place, name_place) values (193, 'Aghada');
insert into place (id_place, name_place) values (194, 'Xigou');
insert into place (id_place, name_place) values (195, 'Bąków');
insert into place (id_place, name_place) values (196, 'Shiye');
insert into place (id_place, name_place) values (197, 'Barreiros');
insert into place (id_place, name_place) values (198, 'Leran Kulon');
insert into place (id_place, name_place) values (199, 'Limeiras');
insert into place (id_place, name_place) values (200, 'Mesiméri');
insert into place (id_place, name_place) values (201, 'Mulleriyawa');
insert into place (id_place, name_place) values (202, 'Drogomyśl');
insert into place (id_place, name_place) values (203, 'Huangjiabu');
insert into place (id_place, name_place) values (204, 'Novopokrovka');
insert into place (id_place, name_place) values (205, 'Gabès');
insert into place (id_place, name_place) values (206, 'Galapa');
insert into place (id_place, name_place) values (207, 'Penedo');
insert into place (id_place, name_place) values (208, 'Talok');
insert into place (id_place, name_place) values (209, 'Tsybulevka');
insert into place (id_place, name_place) values (210, 'Stronie');
insert into place (id_place, name_place) values (211, 'Wang Sombun');
insert into place (id_place, name_place) values (212, 'Thị Trấn Mường Khương');
insert into place (id_place, name_place) values (213, 'Cluny');
insert into place (id_place, name_place) values (214, 'Stanovoye');
insert into place (id_place, name_place) values (215, 'Kuching');
insert into place (id_place, name_place) values (216, 'Sośnie');
insert into place (id_place, name_place) values (217, 'Stalís');
insert into place (id_place, name_place) values (218, 'Shizuoka-shi');
insert into place (id_place, name_place) values (219, 'Bendo');
insert into place (id_place, name_place) values (220, 'Beishan');
insert into place (id_place, name_place) values (221, 'Patos');
insert into place (id_place, name_place) values (222, 'Arjawinangun');
insert into place (id_place, name_place) values (223, 'Saint-Bruno-de-Montarville');
insert into place (id_place, name_place) values (224, 'Sevilla');
insert into place (id_place, name_place) values (225, 'Cibitung');
insert into place (id_place, name_place) values (226, 'Nagoya-shi');
insert into place (id_place, name_place) values (227, 'Kebili');
insert into place (id_place, name_place) values (228, 'Frösön');
insert into place (id_place, name_place) values (229, 'Kwangyang');
insert into place (id_place, name_place) values (230, 'Palauig');
insert into place (id_place, name_place) values (231, 'Cikole');
insert into place (id_place, name_place) values (232, 'Cajamar');
insert into place (id_place, name_place) values (233, 'Armenia');
insert into place (id_place, name_place) values (234, 'Leeds');
insert into place (id_place, name_place) values (235, 'Đống Đa');
insert into place (id_place, name_place) values (236, 'San Rafael Petzal');
insert into place (id_place, name_place) values (237, 'Mobara');
insert into place (id_place, name_place) values (238, 'Fulong');
insert into place (id_place, name_place) values (239, 'Segezha');
insert into place (id_place, name_place) values (240, 'Musan-ŭp');
insert into place (id_place, name_place) values (241, 'Curug');
insert into place (id_place, name_place) values (242, 'Zhuyang');
insert into place (id_place, name_place) values (243, 'Trinidad');
insert into place (id_place, name_place) values (244, 'Pregradnaya');
insert into place (id_place, name_place) values (245, 'Pringu');
insert into place (id_place, name_place) values (246, 'Ban Khok');
insert into place (id_place, name_place) values (247, 'Daqian');
insert into place (id_place, name_place) values (248, 'Leworook');
insert into place (id_place, name_place) values (249, 'Oljoq');
insert into place (id_place, name_place) values (250, 'Tianyu');
insert into place (id_place, name_place) values (251, 'Hrib-Loški Potok');
insert into place (id_place, name_place) values (252, 'Karlstad');
insert into place (id_place, name_place) values (253, 'Jinghong');
insert into place (id_place, name_place) values (254, 'Kaabong');
insert into place (id_place, name_place) values (255, 'Sukabumi');
insert into place (id_place, name_place) values (256, 'Lanas');
insert into place (id_place, name_place) values (257, 'Gumuk Tengah');
insert into place (id_place, name_place) values (258, 'Aveiras de Cima');
insert into place (id_place, name_place) values (259, 'Māmūnīyeh');
insert into place (id_place, name_place) values (260, 'Huangcun');
insert into place (id_place, name_place) values (261, 'Ampanihy');
insert into place (id_place, name_place) values (262, 'Aḑ Ḑil‘');
insert into place (id_place, name_place) values (263, 'Susuman');
insert into place (id_place, name_place) values (264, 'Buket Teukuh');
insert into place (id_place, name_place) values (265, 'Ketapang');
insert into place (id_place, name_place) values (266, 'Mellieħa');
insert into place (id_place, name_place) values (267, 'Mỹ Tho');
insert into place (id_place, name_place) values (268, 'Santa Luzia');
insert into place (id_place, name_place) values (269, 'Karangasem');
insert into place (id_place, name_place) values (270, 'Ballsh');
insert into place (id_place, name_place) values (271, 'Ngrambitan');
insert into place (id_place, name_place) values (272, 'Jiangcun');
insert into place (id_place, name_place) values (273, 'Nioumamilima');
insert into place (id_place, name_place) values (274, 'Muñoz East');
insert into place (id_place, name_place) values (275, 'Itamarandiba');
insert into place (id_place, name_place) values (276, 'Parikkala');
insert into place (id_place, name_place) values (277, 'Kiruna');
insert into place (id_place, name_place) values (278, 'Svetlograd');
insert into place (id_place, name_place) values (279, 'Meget');
insert into place (id_place, name_place) values (280, 'Cahors');
insert into place (id_place, name_place) values (281, 'Zhangguanying');
insert into place (id_place, name_place) values (282, 'Baozi');
insert into place (id_place, name_place) values (283, 'Straldzha');
insert into place (id_place, name_place) values (284, 'Betioky');
insert into place (id_place, name_place) values (285, 'Kilkenny');
insert into place (id_place, name_place) values (286, 'Santana');
insert into place (id_place, name_place) values (287, 'Santa Luzia');
insert into place (id_place, name_place) values (288, 'Xianghe');
insert into place (id_place, name_place) values (289, 'Terawas');
insert into place (id_place, name_place) values (290, 'Palaihari');
insert into place (id_place, name_place) values (291, 'Nong Bun Nak');
insert into place (id_place, name_place) values (292, 'Aurora');
insert into place (id_place, name_place) values (293, 'Xiaolan');
insert into place (id_place, name_place) values (294, 'Carcavelos');
insert into place (id_place, name_place) values (295, 'Timbiras');
insert into place (id_place, name_place) values (296, 'Tigaon');
insert into place (id_place, name_place) values (297, 'Carmo do Paranaíba');
insert into place (id_place, name_place) values (298, 'Matumadua');
insert into place (id_place, name_place) values (299, 'Nagrak');
insert into place (id_place, name_place) values (300, 'København');
insert into place (id_place, name_place) values (301, 'Hanji');
insert into place (id_place, name_place) values (302, 'Thorpe');
insert into place (id_place, name_place) values (303, 'Ciomas');
insert into place (id_place, name_place) values (304, 'Albany');
insert into place (id_place, name_place) values (305, 'Sukaratu');
insert into place (id_place, name_place) values (306, 'Tembisa');
insert into place (id_place, name_place) values (307, 'Bangassou');
insert into place (id_place, name_place) values (308, 'Dýšina');
insert into place (id_place, name_place) values (309, 'Ōyama');
insert into place (id_place, name_place) values (310, 'Klerksdorp');
insert into place (id_place, name_place) values (311, 'Puerto Castilla');
insert into place (id_place, name_place) values (312, 'Firavitoba');
insert into place (id_place, name_place) values (313, 'Uvarovo');
insert into place (id_place, name_place) values (314, 'Takāb');
insert into place (id_place, name_place) values (315, 'Santa Cruz de El Seibo');
insert into place (id_place, name_place) values (316, 'Qianqiao');
insert into place (id_place, name_place) values (317, 'Ancenis');
insert into place (id_place, name_place) values (318, 'Pale');
insert into place (id_place, name_place) values (319, 'Gengcheng');
insert into place (id_place, name_place) values (320, 'Banjar Petak');
insert into place (id_place, name_place) values (321, 'Yŏng-dong');
insert into place (id_place, name_place) values (322, 'Sanchang');
insert into place (id_place, name_place) values (323, 'San Francisco');
insert into place (id_place, name_place) values (324, 'San Isidro');
insert into place (id_place, name_place) values (325, 'Newmarket');
insert into place (id_place, name_place) values (326, 'Kiambu');
insert into place (id_place, name_place) values (327, 'Taza');
insert into place (id_place, name_place) values (328, 'Falun');
insert into place (id_place, name_place) values (329, 'Al Badārī');
insert into place (id_place, name_place) values (330, 'Farafangana');
insert into place (id_place, name_place) values (331, 'Al Wuday‘');
insert into place (id_place, name_place) values (332, 'Qixingtai');
insert into place (id_place, name_place) values (333, 'Salavan');
insert into place (id_place, name_place) values (334, 'Manzanillo');
insert into place (id_place, name_place) values (335, 'El Águila');
insert into place (id_place, name_place) values (336, 'Padangguci');
insert into place (id_place, name_place) values (337, 'Beaverton');
insert into place (id_place, name_place) values (338, 'Asopía');
insert into place (id_place, name_place) values (339, 'Zhongping');
insert into place (id_place, name_place) values (340, 'Ibung');
insert into place (id_place, name_place) values (341, 'Claremont');
insert into place (id_place, name_place) values (342, 'Hexi');
insert into place (id_place, name_place) values (343, 'At Tāj');
insert into place (id_place, name_place) values (344, 'Zernograd');
insert into place (id_place, name_place) values (345, 'Yinla');
insert into place (id_place, name_place) values (346, 'Xiehu');
insert into place (id_place, name_place) values (347, 'Dongle');
insert into place (id_place, name_place) values (348, 'Staraya Ladoga');
insert into place (id_place, name_place) values (349, 'Carolina');
insert into place (id_place, name_place) values (350, 'Phak Hai');
insert into place (id_place, name_place) values (351, 'Kiel');
insert into place (id_place, name_place) values (352, 'Huayuan');
insert into place (id_place, name_place) values (353, 'Kỳ Anh');
insert into place (id_place, name_place) values (354, 'Potou');
insert into place (id_place, name_place) values (355, 'Goya');
insert into place (id_place, name_place) values (356, 'Svetlyy Yar');
insert into place (id_place, name_place) values (357, 'Houxixi');
insert into place (id_place, name_place) values (358, 'Boulogne-Billancourt');
insert into place (id_place, name_place) values (359, 'Nanguzhuang');
insert into place (id_place, name_place) values (360, 'Buenavista');
insert into place (id_place, name_place) values (361, 'Longju');
insert into place (id_place, name_place) values (362, 'Independencia');
insert into place (id_place, name_place) values (363, 'Kamionka');
insert into place (id_place, name_place) values (364, 'Bressuire');
insert into place (id_place, name_place) values (365, 'Ngawi');
insert into place (id_place, name_place) values (366, 'Lahat');
insert into place (id_place, name_place) values (367, 'Songqiao');
insert into place (id_place, name_place) values (368, 'Ipala');
insert into place (id_place, name_place) values (369, 'Martapura');
insert into place (id_place, name_place) values (370, 'Jargalant');
insert into place (id_place, name_place) values (371, 'San Bernardino');
insert into place (id_place, name_place) values (372, 'Tagbilaran City');
insert into place (id_place, name_place) values (373, 'Manogay');
insert into place (id_place, name_place) values (374, 'Pyhäntä');
insert into place (id_place, name_place) values (375, 'Dayu');
insert into place (id_place, name_place) values (376, 'Qiubin');
insert into place (id_place, name_place) values (377, 'Zhaodong');
insert into place (id_place, name_place) values (378, 'Lebedyan’');
insert into place (id_place, name_place) values (379, 'Karney Shomron');
insert into place (id_place, name_place) values (380, 'Kampen (Overijssel)');
insert into place (id_place, name_place) values (381, 'Krasnodar');
insert into place (id_place, name_place) values (382, 'Ormož');
insert into place (id_place, name_place) values (383, 'Sundsvall');
insert into place (id_place, name_place) values (384, 'Palaiochóri');
insert into place (id_place, name_place) values (385, 'Dalazi');
insert into place (id_place, name_place) values (386, 'Bílovice');
insert into place (id_place, name_place) values (387, 'Komoro');
insert into place (id_place, name_place) values (388, 'Salamina');
insert into place (id_place, name_place) values (389, 'Mehrān');
insert into place (id_place, name_place) values (390, 'Linxi');
insert into place (id_place, name_place) values (391, 'Brodokalmak');
insert into place (id_place, name_place) values (392, 'Vurğun');
insert into place (id_place, name_place) values (393, 'Hutou');
insert into place (id_place, name_place) values (394, 'Isyangulovo');
insert into place (id_place, name_place) values (395, 'Itapicuru');
insert into place (id_place, name_place) values (396, 'Oslo');
insert into place (id_place, name_place) values (397, 'Qimeng');
insert into place (id_place, name_place) values (398, 'Longhua');
insert into place (id_place, name_place) values (399, 'Maurisu');
insert into place (id_place, name_place) values (400, 'Jīwani');
insert into place (id_place, name_place) values (401, 'Otaru');
insert into place (id_place, name_place) values (402, 'Mukhen');
insert into place (id_place, name_place) values (403, 'Votkinsk');
insert into place (id_place, name_place) values (404, 'Somovo');
insert into place (id_place, name_place) values (405, 'Tamorong');
insert into place (id_place, name_place) values (406, 'La Plaine-Saint-Denis');
insert into place (id_place, name_place) values (407, 'Shangyong');
insert into place (id_place, name_place) values (408, 'Ryazhsk');
insert into place (id_place, name_place) values (409, 'Bambari');
insert into place (id_place, name_place) values (410, 'Severskaya');
insert into place (id_place, name_place) values (411, 'Conner');
insert into place (id_place, name_place) values (412, 'Štítina');
insert into place (id_place, name_place) values (413, 'Rumelange');
insert into place (id_place, name_place) values (414, 'Datar');
insert into place (id_place, name_place) values (415, 'Armenta');
insert into place (id_place, name_place) values (416, 'Krajan');
insert into place (id_place, name_place) values (417, 'Beloeil');
insert into place (id_place, name_place) values (418, 'Non Sung');
insert into place (id_place, name_place) values (419, 'Minneapolis');
insert into place (id_place, name_place) values (420, 'Shiraoi');
insert into place (id_place, name_place) values (421, 'Österbybruk');
insert into place (id_place, name_place) values (422, 'Simi Valley');
insert into place (id_place, name_place) values (423, 'Moravská Třebová');
insert into place (id_place, name_place) values (424, 'Paris 05');
insert into place (id_place, name_place) values (425, 'Tuopu');
insert into place (id_place, name_place) values (426, 'Zhangdiyingzi');
insert into place (id_place, name_place) values (427, 'Huacheng');
insert into place (id_place, name_place) values (428, 'Villaguay');
insert into place (id_place, name_place) values (429, 'Bierawa');
insert into place (id_place, name_place) values (430, 'Šardice');
insert into place (id_place, name_place) values (431, 'Montor Timur');
insert into place (id_place, name_place) values (432, 'Cikaras');
insert into place (id_place, name_place) values (433, 'Algés');
insert into place (id_place, name_place) values (434, 'Regnów');
insert into place (id_place, name_place) values (435, 'Bunawan');
insert into place (id_place, name_place) values (436, 'Bromma');
insert into place (id_place, name_place) values (437, 'Kizel');
insert into place (id_place, name_place) values (438, 'Pagaden');
insert into place (id_place, name_place) values (439, 'Villa del Carmen');
insert into place (id_place, name_place) values (440, 'Galveias');
insert into place (id_place, name_place) values (441, 'Tuanchengshan');
insert into place (id_place, name_place) values (442, 'Sandgerði');
insert into place (id_place, name_place) values (443, 'Wenwucao');
insert into place (id_place, name_place) values (444, 'Andrijevica');
insert into place (id_place, name_place) values (445, 'Myronivka');
insert into place (id_place, name_place) values (446, 'Khlong Toei');
insert into place (id_place, name_place) values (447, 'Bulawayo');
insert into place (id_place, name_place) values (448, 'Puubheto');
insert into place (id_place, name_place) values (449, 'Staryye Atagi');
insert into place (id_place, name_place) values (450, 'Yajiwa');
insert into place (id_place, name_place) values (451, 'Guadalupe');
insert into place (id_place, name_place) values (452, 'San Gil');
insert into place (id_place, name_place) values (453, 'Dawu');
insert into place (id_place, name_place) values (454, 'Mompós');
insert into place (id_place, name_place) values (455, 'Krajan Siki');
insert into place (id_place, name_place) values (456, 'Lysá nad Labem');
insert into place (id_place, name_place) values (457, 'Kungälv');
insert into place (id_place, name_place) values (458, 'Pacapausa');
insert into place (id_place, name_place) values (459, 'Jimaguayú');
insert into place (id_place, name_place) values (460, 'Qingxi');
insert into place (id_place, name_place) values (461, 'Cipinang');
insert into place (id_place, name_place) values (462, 'Vroutek');
insert into place (id_place, name_place) values (463, 'Trbovlje');
insert into place (id_place, name_place) values (464, 'Dashiju');
insert into place (id_place, name_place) values (465, 'Daxing');
insert into place (id_place, name_place) values (466, 'Tupambaé');
insert into place (id_place, name_place) values (467, 'Ziketan');
insert into place (id_place, name_place) values (468, 'Rivas');
insert into place (id_place, name_place) values (469, 'Liliana');
insert into place (id_place, name_place) values (470, 'Farsta');
insert into place (id_place, name_place) values (471, 'Sarandi');
insert into place (id_place, name_place) values (472, 'San Juan de Limay');
insert into place (id_place, name_place) values (473, 'Staraya Ladoga');
insert into place (id_place, name_place) values (474, 'Staré Hradiště');
insert into place (id_place, name_place) values (475, 'Capalonga');
insert into place (id_place, name_place) values (476, 'Cikondang');
insert into place (id_place, name_place) values (477, 'Néa Vrasná');
insert into place (id_place, name_place) values (478, 'Andop');
insert into place (id_place, name_place) values (479, 'Stockholm');
insert into place (id_place, name_place) values (480, 'Shigou');
insert into place (id_place, name_place) values (481, 'Hetou');
insert into place (id_place, name_place) values (482, 'Chepo');
insert into place (id_place, name_place) values (483, 'Vacaria');
insert into place (id_place, name_place) values (484, 'Anápolis');
insert into place (id_place, name_place) values (485, 'Bajingzi');
insert into place (id_place, name_place) values (486, 'Araras');
insert into place (id_place, name_place) values (487, 'Tuchola');
insert into place (id_place, name_place) values (488, 'Bangbayang');
insert into place (id_place, name_place) values (489, 'Les Clayes-sous-Bois');
insert into place (id_place, name_place) values (490, 'Shapa');
insert into place (id_place, name_place) values (491, 'Tapan');
insert into place (id_place, name_place) values (492, 'Jianyi');
insert into place (id_place, name_place) values (493, 'Antwerpen');
insert into place (id_place, name_place) values (494, 'Erdaocha');
insert into place (id_place, name_place) values (495, 'Selemadeg Kelod');
insert into place (id_place, name_place) values (496, 'Tarczyn');
insert into place (id_place, name_place) values (497, 'Ordzhonikidzevskiy');
insert into place (id_place, name_place) values (498, 'Zheshan');
insert into place (id_place, name_place) values (499, 'Stráž nad Nisou');
insert into place (id_place, name_place) values (500, 'Ronggo');
insert into place (id_place, name_place) values (501, 'Miandrivazo');
insert into place (id_place, name_place) values (502, 'Casa Nova');
insert into place (id_place, name_place) values (503, 'Ranambeling');
insert into place (id_place, name_place) values (504, 'Picton');
insert into place (id_place, name_place) values (505, 'Brits');
insert into place (id_place, name_place) values (506, 'Youyun');
insert into place (id_place, name_place) values (507, 'Kugesi');
insert into place (id_place, name_place) values (508, 'Ya’ngan');
insert into place (id_place, name_place) values (509, 'Kaji');
insert into place (id_place, name_place) values (510, 'Qaffīn');
insert into place (id_place, name_place) values (511, 'Aqtoghay');
insert into place (id_place, name_place) values (512, 'Brzeźnica');
insert into place (id_place, name_place) values (513, 'Chapayeve');
insert into place (id_place, name_place) values (514, 'Szolnok');
insert into place (id_place, name_place) values (515, 'Shōbu');
insert into place (id_place, name_place) values (516, 'Anto');
insert into place (id_place, name_place) values (517, 'Huangjiabu');
insert into place (id_place, name_place) values (518, 'Šibenik');
insert into place (id_place, name_place) values (519, 'Naranjal');
insert into place (id_place, name_place) values (520, 'Shalizhai');
insert into place (id_place, name_place) values (521, 'New York City');
insert into place (id_place, name_place) values (522, 'Yuanjue');
insert into place (id_place, name_place) values (523, 'Kanshan');
insert into place (id_place, name_place) values (524, 'Tomislavgrad');
insert into place (id_place, name_place) values (525, 'Tsukumiura');
insert into place (id_place, name_place) values (526, 'Monywa');
insert into place (id_place, name_place) values (527, 'Cagayan');
insert into place (id_place, name_place) values (528, 'Preston');
insert into place (id_place, name_place) values (529, 'Jedlnia-Letnisko');
insert into place (id_place, name_place) values (530, 'Lewokluok');
insert into place (id_place, name_place) values (531, 'Lyeskawka');
insert into place (id_place, name_place) values (532, 'Emplak');
insert into place (id_place, name_place) values (533, 'Wuluhan');
insert into place (id_place, name_place) values (534, 'Borås');
insert into place (id_place, name_place) values (535, 'Tekeli');
insert into place (id_place, name_place) values (536, 'Paraiso');
insert into place (id_place, name_place) values (537, 'Oskarshamn');
insert into place (id_place, name_place) values (538, 'Nogueira');
insert into place (id_place, name_place) values (539, 'Bipolo');
insert into place (id_place, name_place) values (540, 'Eirado');
insert into place (id_place, name_place) values (541, 'Jelsa');
insert into place (id_place, name_place) values (542, 'Szemud');
insert into place (id_place, name_place) values (543, 'Lom Sak');
insert into place (id_place, name_place) values (544, 'Alibunan');
insert into place (id_place, name_place) values (545, 'Spas-Klepiki');
insert into place (id_place, name_place) values (546, 'Vorob’yovo');
insert into place (id_place, name_place) values (547, 'Salaza');
insert into place (id_place, name_place) values (548, 'Kuangshan');
insert into place (id_place, name_place) values (549, 'Sumberkindagan');
insert into place (id_place, name_place) values (550, 'Shcherbinka');
insert into place (id_place, name_place) values (551, 'Longwood');
insert into place (id_place, name_place) values (552, 'Caucagüito');
insert into place (id_place, name_place) values (553, 'Biguaçu');
insert into place (id_place, name_place) values (554, 'Ciomas');
insert into place (id_place, name_place) values (555, 'Padangpanjang');
insert into place (id_place, name_place) values (556, 'Longshan');
insert into place (id_place, name_place) values (557, 'Yanai');
insert into place (id_place, name_place) values (558, 'Pyrgetós');
insert into place (id_place, name_place) values (559, 'Shaoha');
insert into place (id_place, name_place) values (560, 'Karangtengah Lor');
insert into place (id_place, name_place) values (561, 'Imbituva');
insert into place (id_place, name_place) values (562, 'Yemva');
insert into place (id_place, name_place) values (563, 'Chumphon');
insert into place (id_place, name_place) values (564, 'Templeogue');
insert into place (id_place, name_place) values (565, 'Vera');
insert into place (id_place, name_place) values (566, 'Wuxue Shi');
insert into place (id_place, name_place) values (567, 'Clermont-Ferrand');
insert into place (id_place, name_place) values (568, 'Gaosheng');
insert into place (id_place, name_place) values (569, 'Ängelholm');
insert into place (id_place, name_place) values (570, 'Dongping');
insert into place (id_place, name_place) values (571, 'Manadhoo');
insert into place (id_place, name_place) values (572, 'Lethem');
insert into place (id_place, name_place) values (573, 'Mykonos');
insert into place (id_place, name_place) values (574, 'Troyan');
insert into place (id_place, name_place) values (575, 'Huarong');
insert into place (id_place, name_place) values (576, 'Dū Qal‘ah');
insert into place (id_place, name_place) values (577, 'Tegalsari');
insert into place (id_place, name_place) values (578, 'Novogurovskiy');
insert into place (id_place, name_place) values (579, 'Dulangan');
insert into place (id_place, name_place) values (580, 'Ash Shuqayrah');
insert into place (id_place, name_place) values (581, 'Xinminxiang');
insert into place (id_place, name_place) values (582, 'Paris 12');
insert into place (id_place, name_place) values (583, 'Fatufaun');
insert into place (id_place, name_place) values (584, 'Kadukaung');
insert into place (id_place, name_place) values (585, 'Krajanjugosari');
insert into place (id_place, name_place) values (586, 'Parakanhonje Wetan');
insert into place (id_place, name_place) values (587, 'Pateros');
insert into place (id_place, name_place) values (588, 'Chadong');
insert into place (id_place, name_place) values (589, 'Askim');
insert into place (id_place, name_place) values (590, 'Yaodu');
insert into place (id_place, name_place) values (591, 'Xiahan');
insert into place (id_place, name_place) values (592, 'Durham');
insert into place (id_place, name_place) values (593, 'Jialu');
insert into place (id_place, name_place) values (594, 'Qianying');
insert into place (id_place, name_place) values (595, 'Rusocice');
insert into place (id_place, name_place) values (596, 'Godziszów Pierwszy');
insert into place (id_place, name_place) values (597, 'Dazhongzhuang');
insert into place (id_place, name_place) values (598, 'Líbano');
insert into place (id_place, name_place) values (599, 'Prilep');
insert into place (id_place, name_place) values (600, 'Ryczywół');
insert into place (id_place, name_place) values (601, 'Vinces');
insert into place (id_place, name_place) values (602, 'Belém');
insert into place (id_place, name_place) values (603, 'Santiago do Cacém');
insert into place (id_place, name_place) values (604, 'Vetlanda');
insert into place (id_place, name_place) values (605, 'Xinying');
insert into place (id_place, name_place) values (606, 'Krasnovishersk');
insert into place (id_place, name_place) values (607, 'Leeuwarden');
insert into place (id_place, name_place) values (608, 'Santos Dumont');
insert into place (id_place, name_place) values (609, 'Caraguatatuba');
insert into place (id_place, name_place) values (610, 'Jahrom');
insert into place (id_place, name_place) values (611, 'Kwekwe');
insert into place (id_place, name_place) values (612, 'Gushan');
insert into place (id_place, name_place) values (613, 'Heku');
insert into place (id_place, name_place) values (614, 'San Ignacio de Tupile');
insert into place (id_place, name_place) values (615, 'Tonekābon');
insert into place (id_place, name_place) values (616, 'Örebro');
insert into place (id_place, name_place) values (617, 'Colca');
insert into place (id_place, name_place) values (618, 'Dateng');
insert into place (id_place, name_place) values (619, 'Wenling');
insert into place (id_place, name_place) values (620, 'Sindangjawa');
insert into place (id_place, name_place) values (621, 'Montasik');
insert into place (id_place, name_place) values (622, 'Lukou');
insert into place (id_place, name_place) values (623, 'San Francisco');
insert into place (id_place, name_place) values (624, 'Santa Monica');
insert into place (id_place, name_place) values (625, 'Horní Štěpánov');
insert into place (id_place, name_place) values (626, 'Huyuan');
insert into place (id_place, name_place) values (627, 'Bagumbayan');
insert into place (id_place, name_place) values (628, 'San Juan de Mata');
insert into place (id_place, name_place) values (629, 'Mengla');
insert into place (id_place, name_place) values (630, 'Luleå');
insert into place (id_place, name_place) values (631, 'Aloja');
insert into place (id_place, name_place) values (632, 'Wangcao');
insert into place (id_place, name_place) values (633, 'Benito Juarez');
insert into place (id_place, name_place) values (634, 'Petaling Jaya');
insert into place (id_place, name_place) values (635, 'Anopog');
insert into place (id_place, name_place) values (636, 'Szelków');
insert into place (id_place, name_place) values (637, 'Azurduy');
insert into place (id_place, name_place) values (638, 'Donggaocun');
insert into place (id_place, name_place) values (639, 'New Washington');
insert into place (id_place, name_place) values (640, 'Sukoanyar');
insert into place (id_place, name_place) values (641, 'Denver');
insert into place (id_place, name_place) values (642, 'Sukhirin');
insert into place (id_place, name_place) values (643, 'Padej');
insert into place (id_place, name_place) values (644, 'Esmeraldas');
insert into place (id_place, name_place) values (645, 'Hadyach');
insert into place (id_place, name_place) values (646, 'Kentau');
insert into place (id_place, name_place) values (647, 'Kuala Lumpur');
insert into place (id_place, name_place) values (648, 'Tolbazy');
insert into place (id_place, name_place) values (649, 'Varennes');
insert into place (id_place, name_place) values (650, 'Laolong');
insert into place (id_place, name_place) values (651, 'Waru');
insert into place (id_place, name_place) values (652, 'Na''ale');
insert into place (id_place, name_place) values (653, 'Ozurgeti');
insert into place (id_place, name_place) values (654, 'Huangzhuang');
insert into place (id_place, name_place) values (655, 'Araxá');
insert into place (id_place, name_place) values (656, 'Santa Maria');
insert into place (id_place, name_place) values (657, 'Popovi');
insert into place (id_place, name_place) values (658, 'Xingren');
insert into place (id_place, name_place) values (659, 'Ylöjärvi');
insert into place (id_place, name_place) values (660, 'Baoping');
insert into place (id_place, name_place) values (661, 'Bella Vista');
insert into place (id_place, name_place) values (662, 'Dongdong');
insert into place (id_place, name_place) values (663, 'Jiangxiangzhen');
insert into place (id_place, name_place) values (664, 'Pechora');
insert into place (id_place, name_place) values (665, 'Majennang');
insert into place (id_place, name_place) values (666, 'Dawa-Dawa');
insert into place (id_place, name_place) values (667, 'Baiquesi');
insert into place (id_place, name_place) values (668, 'Kalugmanan');
insert into place (id_place, name_place) values (669, 'Lere');
insert into place (id_place, name_place) values (670, 'Rennes');
insert into place (id_place, name_place) values (671, 'Aparecida do Taboado');
insert into place (id_place, name_place) values (672, 'Dongshan');
insert into place (id_place, name_place) values (673, 'Taganak');
insert into place (id_place, name_place) values (674, 'Aylmer');
insert into place (id_place, name_place) values (675, 'Erjiegou');
insert into place (id_place, name_place) values (676, 'West Palm Beach');
insert into place (id_place, name_place) values (677, 'Tuchlovice');
insert into place (id_place, name_place) values (678, 'Carvalho');
insert into place (id_place, name_place) values (679, 'Kapiri Mposhi');
insert into place (id_place, name_place) values (680, 'Firenze');
insert into place (id_place, name_place) values (681, 'Druju');
insert into place (id_place, name_place) values (682, 'Maomiaoji');
insert into place (id_place, name_place) values (683, 'Avignon');
insert into place (id_place, name_place) values (684, 'Yunxi');
insert into place (id_place, name_place) values (685, 'Fristad');
insert into place (id_place, name_place) values (686, 'Leone');
insert into place (id_place, name_place) values (687, 'Puerto Barrios');
insert into place (id_place, name_place) values (688, 'Umm Ruwaba');
insert into place (id_place, name_place) values (689, 'Gongnong');
insert into place (id_place, name_place) values (690, 'Dorowa Mining Lease');
insert into place (id_place, name_place) values (691, 'Kristiansand S');
insert into place (id_place, name_place) values (692, 'Zhaojia');
insert into place (id_place, name_place) values (693, 'Dalakovo');
insert into place (id_place, name_place) values (694, 'Bryan');
insert into place (id_place, name_place) values (695, 'Tiztoutine');
insert into place (id_place, name_place) values (696, 'Kuczbork-Osada');
insert into place (id_place, name_place) values (697, 'Rymättylä');
insert into place (id_place, name_place) values (698, 'Casa Quemada');
insert into place (id_place, name_place) values (699, 'Mattaldi');
insert into place (id_place, name_place) values (700, 'Mamara');
insert into place (id_place, name_place) values (701, 'Dzięgielów');
insert into place (id_place, name_place) values (702, 'Fteliá');
insert into place (id_place, name_place) values (703, 'Sumurnanjung');
insert into place (id_place, name_place) values (704, 'San Julian');
insert into place (id_place, name_place) values (705, 'Wangqu');
insert into place (id_place, name_place) values (706, 'Yeping');
insert into place (id_place, name_place) values (707, 'Tanashichō');
insert into place (id_place, name_place) values (708, 'Kaliningrad');
insert into place (id_place, name_place) values (709, 'Chantal');
insert into place (id_place, name_place) values (710, 'Eksjö');
insert into place (id_place, name_place) values (711, 'Meziměstí');
insert into place (id_place, name_place) values (712, 'Biryukove');
insert into place (id_place, name_place) values (713, 'Nariño');
insert into place (id_place, name_place) values (714, 'Nice');
insert into place (id_place, name_place) values (715, 'Muktāgācha');
insert into place (id_place, name_place) values (716, 'Kaset Sombun');
insert into place (id_place, name_place) values (717, 'Brikama Nding');
insert into place (id_place, name_place) values (718, 'Siparia');
insert into place (id_place, name_place) values (719, 'Norrahammar');
insert into place (id_place, name_place) values (720, 'Vakhtan');
insert into place (id_place, name_place) values (721, 'San Jose');
insert into place (id_place, name_place) values (722, 'Tiantai Chengguanzhen');
insert into place (id_place, name_place) values (723, 'Shahumyan');
insert into place (id_place, name_place) values (724, 'Al Jīb');
insert into place (id_place, name_place) values (725, 'Wangjiachang');
insert into place (id_place, name_place) values (726, 'Daxinshao');
insert into place (id_place, name_place) values (727, 'Virovitica');
insert into place (id_place, name_place) values (728, 'Zhalinghu');
insert into place (id_place, name_place) values (729, 'Erdenet');
insert into place (id_place, name_place) values (730, 'Guilhabreu');
insert into place (id_place, name_place) values (731, 'Dunaivtsi');
insert into place (id_place, name_place) values (732, 'Maraial');
insert into place (id_place, name_place) values (733, 'Jiaocun');
insert into place (id_place, name_place) values (734, 'Harjavalta');
insert into place (id_place, name_place) values (735, 'Eenhana');
insert into place (id_place, name_place) values (736, 'Erandique');
insert into place (id_place, name_place) values (737, 'Norberg');
insert into place (id_place, name_place) values (738, 'Beo');
insert into place (id_place, name_place) values (739, 'Bangan-Oda');
insert into place (id_place, name_place) values (740, 'Ruixi');
insert into place (id_place, name_place) values (741, 'São Francisco do Conde');
insert into place (id_place, name_place) values (742, 'Longxi');
insert into place (id_place, name_place) values (743, 'Sarukhan');
insert into place (id_place, name_place) values (744, 'Fengdian');
insert into place (id_place, name_place) values (745, 'Yanas');
insert into place (id_place, name_place) values (746, 'Nanlu');
insert into place (id_place, name_place) values (747, 'Caraballeda');
insert into place (id_place, name_place) values (748, 'Subusub');
insert into place (id_place, name_place) values (749, 'Pingtan');
insert into place (id_place, name_place) values (750, 'Saint John’s');
insert into place (id_place, name_place) values (751, 'Tungoo');
insert into place (id_place, name_place) values (752, 'Crateús');
insert into place (id_place, name_place) values (753, 'Pedra Furada');
insert into place (id_place, name_place) values (754, 'Quinjalca');
insert into place (id_place, name_place) values (755, 'Wuxing');
insert into place (id_place, name_place) values (756, 'Bantengan');
insert into place (id_place, name_place) values (757, 'Daxin');
insert into place (id_place, name_place) values (758, 'Karangsari');
insert into place (id_place, name_place) values (759, 'Alaghsas');
insert into place (id_place, name_place) values (760, 'Micheng');
insert into place (id_place, name_place) values (761, 'Niort');
insert into place (id_place, name_place) values (762, 'Entre Rios');
insert into place (id_place, name_place) values (763, 'Xinying');
insert into place (id_place, name_place) values (764, 'Mingyihe');
insert into place (id_place, name_place) values (765, 'Chilecito');
insert into place (id_place, name_place) values (766, 'Wielgie');
insert into place (id_place, name_place) values (767, 'Brloh');
insert into place (id_place, name_place) values (768, 'Diapaga');
insert into place (id_place, name_place) values (769, 'Saint-Brieuc');
insert into place (id_place, name_place) values (770, 'Lisui');
insert into place (id_place, name_place) values (771, 'Chattanooga');
insert into place (id_place, name_place) values (772, 'Marka');
insert into place (id_place, name_place) values (773, 'Nangka');
insert into place (id_place, name_place) values (774, 'Bobolice');
insert into place (id_place, name_place) values (775, 'Sambonggede');
insert into place (id_place, name_place) values (776, 'Gradishtë');
insert into place (id_place, name_place) values (777, 'Pukekohe East');
insert into place (id_place, name_place) values (778, 'Paltashaco');
insert into place (id_place, name_place) values (779, 'Maastricht');
insert into place (id_place, name_place) values (780, 'Amagi');
insert into place (id_place, name_place) values (781, 'Jastrzębia Góra');
insert into place (id_place, name_place) values (782, 'Mufumbwe');
insert into place (id_place, name_place) values (783, 'Banjar Bias');
insert into place (id_place, name_place) values (784, 'Fleury-les-Aubrais');
insert into place (id_place, name_place) values (785, 'Lodan Wetan');
insert into place (id_place, name_place) values (786, 'Maintirano');
insert into place (id_place, name_place) values (787, 'Weiyanggong');
insert into place (id_place, name_place) values (788, 'Shancheng');
insert into place (id_place, name_place) values (789, 'Caparrapí');
insert into place (id_place, name_place) values (790, 'Huangban');
insert into place (id_place, name_place) values (791, 'Funabashi');
insert into place (id_place, name_place) values (792, 'Kitahama');
insert into place (id_place, name_place) values (793, 'Gōtsuchō');
insert into place (id_place, name_place) values (794, 'Xiangba');
insert into place (id_place, name_place) values (795, 'Kylmäkoski');
insert into place (id_place, name_place) values (796, 'Ishqoshim');
insert into place (id_place, name_place) values (797, 'Rendeng');
insert into place (id_place, name_place) values (798, 'Zwolle');
insert into place (id_place, name_place) values (799, 'Al Matūn');
insert into place (id_place, name_place) values (800, 'Georgetown');
insert into place (id_place, name_place) values (801, 'Dedenëvo');
insert into place (id_place, name_place) values (802, 'Kurashiki');
insert into place (id_place, name_place) values (803, 'Zarqa');
insert into place (id_place, name_place) values (804, 'Iles');
insert into place (id_place, name_place) values (805, 'Ambat');
insert into place (id_place, name_place) values (806, 'Nangahale');
insert into place (id_place, name_place) values (807, 'Tracal');
insert into place (id_place, name_place) values (808, 'Annan');
insert into place (id_place, name_place) values (809, 'Dukuhmencek Lor');
insert into place (id_place, name_place) values (810, 'Verkhniy Yasenov');
insert into place (id_place, name_place) values (811, 'Taloy');
insert into place (id_place, name_place) values (812, 'San Isidro');
insert into place (id_place, name_place) values (813, 'Sandviken');
insert into place (id_place, name_place) values (814, 'Almere Haven');
insert into place (id_place, name_place) values (815, 'Alès');
insert into place (id_place, name_place) values (816, 'Luopu');
insert into place (id_place, name_place) values (817, 'Władysławowo');
insert into place (id_place, name_place) values (818, 'Xi’an');
insert into place (id_place, name_place) values (819, 'Gizo');
insert into place (id_place, name_place) values (820, 'Cama Juan');
insert into place (id_place, name_place) values (821, 'Qiqian');
insert into place (id_place, name_place) values (822, 'Citeguh');
insert into place (id_place, name_place) values (823, 'San Justo');
insert into place (id_place, name_place) values (824, 'Widorokandang');
insert into place (id_place, name_place) values (825, 'Tagnanan');
insert into place (id_place, name_place) values (826, 'Jing’an');
insert into place (id_place, name_place) values (827, 'Tobias Barreto');
insert into place (id_place, name_place) values (828, 'Gocoton');
insert into place (id_place, name_place) values (829, 'Skelivka');
insert into place (id_place, name_place) values (830, 'Verkhnyachka');
insert into place (id_place, name_place) values (831, 'Kuusjoki');
insert into place (id_place, name_place) values (832, 'Bagahanlad');
insert into place (id_place, name_place) values (833, 'Gaotaizi');
insert into place (id_place, name_place) values (834, 'Lashio');
insert into place (id_place, name_place) values (835, 'Zapolyarnyy');
insert into place (id_place, name_place) values (836, 'Patalan');
insert into place (id_place, name_place) values (837, 'Jingyu');
insert into place (id_place, name_place) values (838, 'Vostok');
insert into place (id_place, name_place) values (839, 'Stockholm');
insert into place (id_place, name_place) values (840, 'Znamenskoye');
insert into place (id_place, name_place) values (841, 'Shangping');
insert into place (id_place, name_place) values (842, 'Fernandópolis');
insert into place (id_place, name_place) values (843, 'Columbia');
insert into place (id_place, name_place) values (844, 'Ed');
insert into place (id_place, name_place) values (845, 'Houston');
insert into place (id_place, name_place) values (846, 'Yên Lạc');
insert into place (id_place, name_place) values (847, 'Changwon');
insert into place (id_place, name_place) values (848, 'Dve Mogili');
insert into place (id_place, name_place) values (849, 'Oujiangcha');
insert into place (id_place, name_place) values (850, 'Sangalhos');
insert into place (id_place, name_place) values (851, 'Milton');
insert into place (id_place, name_place) values (852, 'Baiguo');
insert into place (id_place, name_place) values (853, 'Daohe');
insert into place (id_place, name_place) values (854, 'Ulricehamn');
insert into place (id_place, name_place) values (855, 'Mīāndoāb');
insert into place (id_place, name_place) values (856, 'Xiniqi');
insert into place (id_place, name_place) values (857, 'Zhaotong');
insert into place (id_place, name_place) values (858, 'Lac du Bonnet');
insert into place (id_place, name_place) values (859, 'Duantan');
insert into place (id_place, name_place) values (860, 'Beishan');
insert into place (id_place, name_place) values (861, 'Kořenov');
insert into place (id_place, name_place) values (862, 'Wates');
insert into place (id_place, name_place) values (863, 'Borzechów');
insert into place (id_place, name_place) values (864, 'Lebak Timur');
insert into place (id_place, name_place) values (865, 'Jiashi');
insert into place (id_place, name_place) values (866, 'Cawayan');
insert into place (id_place, name_place) values (867, 'Uppsala');
insert into place (id_place, name_place) values (868, 'Amsterdam Oud Zuid en Rivierenbuurt');
insert into place (id_place, name_place) values (869, 'Dolany');
insert into place (id_place, name_place) values (870, 'Harstad');
insert into place (id_place, name_place) values (871, 'Xundian');
insert into place (id_place, name_place) values (872, 'Zambrów');
insert into place (id_place, name_place) values (873, 'Lengkongjaya');
insert into place (id_place, name_place) values (874, 'Tanjungrejo Lor');
insert into place (id_place, name_place) values (875, 'Divjakë');
insert into place (id_place, name_place) values (876, 'Quinipot');
insert into place (id_place, name_place) values (877, 'Xin’an');
insert into place (id_place, name_place) values (878, 'Nezhinka');
insert into place (id_place, name_place) values (879, 'Igoumenítsa');
insert into place (id_place, name_place) values (880, 'Perechyn');
insert into place (id_place, name_place) values (881, 'Orahovica');
insert into place (id_place, name_place) values (882, 'Itambé');
insert into place (id_place, name_place) values (883, 'Le Havre');
insert into place (id_place, name_place) values (884, 'Jemielno');
insert into place (id_place, name_place) values (885, 'Rizó');
insert into place (id_place, name_place) values (886, 'Goascorán');
insert into place (id_place, name_place) values (887, 'Al Qūşīyah');
insert into place (id_place, name_place) values (888, 'Javhlant');
insert into place (id_place, name_place) values (889, 'Cool űrhajó');
insert into place (id_place, name_place) values (890, 'İsmayıllı');
insert into place (id_place, name_place) values (891, 'Shishan');
insert into place (id_place, name_place) values (892, 'Anastácio');
insert into place (id_place, name_place) values (893, 'Bistrica ob Sotli');
insert into place (id_place, name_place) values (894, 'Zhonghuopu');
insert into place (id_place, name_place) values (895, 'Śródmieście');
insert into place (id_place, name_place) values (896, 'Gorobinci');
insert into place (id_place, name_place) values (897, 'Niort');
insert into place (id_place, name_place) values (898, 'Arras');
insert into place (id_place, name_place) values (899, 'Finzes');
insert into place (id_place, name_place) values (900, 'Hamilton');
insert into place (id_place, name_place) values (901, 'Kirkuk');
insert into place (id_place, name_place) values (902, 'Laveiras');
insert into place (id_place, name_place) values (903, 'Željezno Polje');
insert into place (id_place, name_place) values (904, 'West Palm Beach');
insert into place (id_place, name_place) values (905, 'Nizhniy Tagil');
insert into place (id_place, name_place) values (906, 'Fuxi');
insert into place (id_place, name_place) values (907, 'Świlcza');
insert into place (id_place, name_place) values (908, 'Kuala Lumpur');
insert into place (id_place, name_place) values (909, 'Tercena');
insert into place (id_place, name_place) values (910, 'Delft');
insert into place (id_place, name_place) values (911, 'Curuan');
insert into place (id_place, name_place) values (912, 'Ban Dung');
insert into place (id_place, name_place) values (913, 'Krajan');
insert into place (id_place, name_place) values (914, 'Uglich');
insert into place (id_place, name_place) values (915, 'Bordeaux');
insert into place (id_place, name_place) values (916, 'Paccho');
insert into place (id_place, name_place) values (917, 'Nagu');
insert into place (id_place, name_place) values (918, 'Tianqian');
insert into place (id_place, name_place) values (919, 'Narol');
insert into place (id_place, name_place) values (920, 'Torrijos');
insert into place (id_place, name_place) values (921, 'Lennec');
insert into place (id_place, name_place) values (922, 'Trebisht-Muçinë');
insert into place (id_place, name_place) values (923, 'Riit');
insert into place (id_place, name_place) values (924, 'Cumba');
insert into place (id_place, name_place) values (925, 'Buchou');
insert into place (id_place, name_place) values (926, 'Bekasi');
insert into place (id_place, name_place) values (927, 'Cihideung Satu');
insert into place (id_place, name_place) values (928, 'Voznesenskoye');
insert into place (id_place, name_place) values (929, 'Fiães');
insert into place (id_place, name_place) values (930, 'Yangzi Jianglu');
insert into place (id_place, name_place) values (931, 'Rîşcani');
insert into place (id_place, name_place) values (932, 'Kowŏn-ŭp');
insert into place (id_place, name_place) values (933, 'San Isidro');
insert into place (id_place, name_place) values (934, 'Dajabón');
insert into place (id_place, name_place) values (935, 'Nabunturan');
insert into place (id_place, name_place) values (936, 'Ruma');
insert into place (id_place, name_place) values (937, 'Kuala Pilah');
insert into place (id_place, name_place) values (938, 'Kuala Lumpur');
insert into place (id_place, name_place) values (939, 'Senggapi');
insert into place (id_place, name_place) values (940, 'Hongmiao');
insert into place (id_place, name_place) values (941, 'Monze');
insert into place (id_place, name_place) values (942, 'Atipuluhan');
insert into place (id_place, name_place) values (943, 'Mugi');
insert into place (id_place, name_place) values (944, 'Crnilište');
insert into place (id_place, name_place) values (945, 'Sindangpanji');
insert into place (id_place, name_place) values (946, 'Khelyulya');
insert into place (id_place, name_place) values (947, 'Belo Oriente');
insert into place (id_place, name_place) values (948, 'Baitang');
insert into place (id_place, name_place) values (949, 'Hämeenkoski');
insert into place (id_place, name_place) values (950, 'Thành Phố Ninh Bình');
insert into place (id_place, name_place) values (951, 'Calgary');
insert into place (id_place, name_place) values (952, 'Qiujima');
insert into place (id_place, name_place) values (953, 'Yug');
insert into place (id_place, name_place) values (954, 'Nong Kung Si');
insert into place (id_place, name_place) values (955, 'The Valley');
insert into place (id_place, name_place) values (956, 'Da’anshan');
insert into place (id_place, name_place) values (957, 'Krajan Craken');
insert into place (id_place, name_place) values (958, 'Kardítsa');
insert into place (id_place, name_place) values (959, 'Erling');
insert into place (id_place, name_place) values (960, 'Gambaru');
insert into place (id_place, name_place) values (961, 'Parikkala');
insert into place (id_place, name_place) values (962, 'Bunisari');
insert into place (id_place, name_place) values (963, 'Shanjiao');
insert into place (id_place, name_place) values (964, 'Krajan Alastengah');
insert into place (id_place, name_place) values (965, 'Clondalkin');
insert into place (id_place, name_place) values (966, 'Criuleni');
insert into place (id_place, name_place) values (967, 'Boxholm');
insert into place (id_place, name_place) values (968, 'Rabat');
insert into place (id_place, name_place) values (969, 'Kirkland Lake');
insert into place (id_place, name_place) values (970, 'Al Ḩammāmāt');
insert into place (id_place, name_place) values (971, 'Guajiasi');
insert into place (id_place, name_place) values (972, 'Dorp Tera Kora');
insert into place (id_place, name_place) values (973, 'Cabanbanan');
insert into place (id_place, name_place) values (974, 'Fengcheng');
insert into place (id_place, name_place) values (975, 'Vespasiano');
insert into place (id_place, name_place) values (976, 'Setono');
insert into place (id_place, name_place) values (977, 'Đắk Glei');
insert into place (id_place, name_place) values (978, 'Jequitinhonha');
insert into place (id_place, name_place) values (979, 'Żelistrzewo');
insert into place (id_place, name_place) values (980, 'Krajan Gebangan');
insert into place (id_place, name_place) values (981, 'Miatli');
insert into place (id_place, name_place) values (982, 'Jinchang');
insert into place (id_place, name_place) values (983, 'Tan Sum');
insert into place (id_place, name_place) values (984, 'Fudian');
insert into place (id_place, name_place) values (985, 'Kolomak');
insert into place (id_place, name_place) values (986, 'Pickering');
insert into place (id_place, name_place) values (987, 'Cikalang');
insert into place (id_place, name_place) values (988, 'Stockholm');
insert into place (id_place, name_place) values (989, 'São João da Boa Vista');
insert into place (id_place, name_place) values (990, 'Labrador City');
insert into place (id_place, name_place) values (991, 'Danyang');
insert into place (id_place, name_place) values (992, 'Pavlovka');
insert into place (id_place, name_place) values (993, 'Zhangcun');
insert into place (id_place, name_place) values (994, 'Cibeureum');
insert into place (id_place, name_place) values (995, 'Pagangan');
insert into place (id_place, name_place) values (996, 'Fontainebleau');
insert into place (id_place, name_place) values (997, 'Des Moines');
insert into place (id_place, name_place) values (998, 'Gandra');
insert into place (id_place, name_place) values (999, 'Bogorejo');
insert into place (id_place, name_place) values (1000, 'Liopétri');
